### ISSUE TITLE
Build for MSIL

### ISSUE THREAD

**Issue by rogerk-unifysquare** [drivenet/StructuredFieldValues#1]
I'd like to use your library for another library that also needs to parse some headers according to RFC 8941, and I'd need that library to be targeting `MSIL` instead of `x64`.

Would it be possible for you to target `MSIL` instead of `x64` for your StructuredFieldValues library?

**Comment by onyxmaster** [comment]
Thanks for the request. It should be fixed by 573193022975b47292f7bef57d57a6f9744df27d. Since this is a breaking change I bumped the version to 0.4.1, it should be available on NuGet soon.

**Comment by rogerk-unifysquare** [comment]
Awesome, thanks very much for addressing this so promptly. I just confirmed that the new package works fine with my library now.
